apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: viewpoint

resources:
  - namespace.yaml
  - deployment.yaml
  - httproute.yaml

labels:
  - pairs:
      app.kubernetes.io/part-of: viewpoint
    includeSelectors: false

images:
  - name: onionn/viewpoint-frontend
    newTag: latest
  - name: onionn/viewpoint-backend
    newTag: latest
